### PR TITLE
Added webserver to hosts, fix monitoring address

### PR DESCRIPTION
**Pull request by Timi7007**

### CODE REVIEW

**Comment by oliver** [comment]
Right, the "webserver" group and a single host should be added to the hosts file.
But I think we should rather add a host with name "bremen.freifunk.net", since this Ansible config is meant to set up our real server.

I'm not an Ansible expert and don't know the best practices for this. @mortzu, @jplitza, @corny: what's your opinion on this - should we add a "ssh-Address for webserver goes here" placeholder, or should we hardcode "bremen.freifunk.net" as target server name?

**Comment by Timi7007** [comment]
VPNs have other hostnames...

**Comment by Timi7007** [comment]
webserver is now in your repo, vpn is not your work: Can this pull request be closed?

**Comment by oliver** [comment]
Yes, you are right.

**Pull request closed without merging**
